spring:
  security:
    oauth2:
      client:
        registration:
          clever-client-pkce:
            provider: clever
            client-name: clever-client-pkce
            client-id: 4569bca1-bca7-49eb-a03c-7898e9197d5f
            redirect-uri: 'http://armorauth-demo:8085/login/oauth2/code/clever'
            authorization-grant-type: authorization_code
            client-authentication-method: none
            scope: message.read,message.write,openid
        provider:
          clever:
            authorization-uri: http://armorauth-server:9000/oauth2/authorize
            token-uri: http://armorauth-server:9000/oauth2/token
            jwk-set-uri: http://armorauth-server:9000/oauth2/jwks
