server:
  port: 9000
  servlet:
    session:
      tracking-modes: cookie
spring:
  profiles:
    active: mysql
  application:
    name: armorauth-server
  data:
    redis:
      repositories:
        enabled: false
  jpa:
    show-sql: true
    generate-ddl: false
    open-in-view: false
    database: mysql
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration-mysql,classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
  endpoint:
    health:
      show-details: when-authorized

armorauth:
  federation:
    default-login-mode: confirm
