spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.security.oauth2.client.autoconfigure.OAuth2ClientAutoConfiguration
      - org.springframework.boot.security.oauth2.client.autoconfigure.servlet.OAuth2ClientWebSecurityAutoConfiguration
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./.runtime/h2/identity_server_mock;MODE=MySQL;DATABASE_TO_LOWER=TRUE;NON_KEYWORDS=USER,AUTHORIZATION
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: true
    locations: classpath:db/migration-h2,classpath:db/migration,classpath:db/mock-h2
    baseline-on-migrate: true
    baseline-version: 0
    repair-on-migrate: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: false
    generate-ddl: false
    open-in-view: false
    database: h2
    hibernate:
      ddl-auto: none

armorauth:
  authorization-server:
    multiple-issuers:
      enabled: true
  federation:
    enabled: false
    default-login-mode: confirm
  captcha:
    sms:
      expose-code: true
